### ISSUE TITLE
create themes for ggplot2 and lattice

### ISSUE THREAD

**Issue by beanumber** [beanumber/mdsr#1]

**Comment by nicholasjhorton** [comment]
I like the idea!

**Comment by nicholasjhorton** [comment]
Any updates on this front?

**Comment by beanumber** [comment]
No, but I have been thinking about it. There is an example of a `theme_mdsr` in datavizIII.

**Comment by beanumber** [comment]
I added a `ggplot2` theme. I'm not in love with it -- please feel free to suggest changes.
