### ISSUE TITLE
weirdness in documentation of CountryData2

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/mdsr#14]
There are some stray characters at the end of the variable definitions (e.g. 2147).

<img width="506" alt="screen shot 2016-07-08 at 3 42 19 pm" src="https://cloud.githubusercontent.com/assets/530542/16699525/ab43d3ca-4522-11e6-9942-1c1a0991e50c.png">

**Comment by beanumber** [comment]
This is a much bigger mess. I suggest we trim this down to just the four variables that we actually use in the book.
