### ISSUE TITLE
should this package "Depends" on "mosaic", so that those function load automatically?

### ISSUE THREAD

**Issue by beanumber** [beanumber/mdsr#2]

**Comment by beanumber** [comment]
Moreover, should this package "Imports" all of the packages necessary to compile the book?

**Comment by nicholasjhorton** [comment]
I think not: fewer depends is better I suspect if we want to get this on CRAN.

Nick

> On Oct 7, 2015, at 9:27 AM, Ben Baumer notifications@github.com wrote:
> 
> Moreover, should this package "Imports" all of the packages necessary to compile the book?
> 
> —
> Reply to this email directly or view it on GitHub.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by beanumber** [comment]
It should Depend on `mosaic`.

It should Suggests all the other packages needed to compile the book
