### ISSUE TITLE
Error installing mdsr on datascience.ibm.com

### ISSUE THREAD

**Issue by gmichel-SMU** [beanumber/mdsr#24]
I'm trying to install MDSR but the installtion is failling on using install.packages("mdsr") or devtools::install_github("beanumber/mdsr").

 packageVersion("dbplyr")
Error in packageVersion("dbplyr") : package ‘dbplyr’ not found
> packageVersion("dplyr")
[1] ‘0.5.0’

The installation log is following:
> install.packages("mdsr")
Installing package into ‘/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘dplyr’, ‘dbplyr’

trying URL 'https://cran.rstudio.com/src/contrib/dplyr_0.7.3.tar.gz'
Content type 'unknown' length 807897 bytes (788 KB)
==================================================
downloaded 788 KB

trying URL 'https://cran.rstudio.com/src/contrib/dbplyr_1.1.0.tar.gz'
Content type 'unknown' length 247062 bytes (241 KB)
==================================================
downloaded 241 KB

trying URL 'https://cran.rstudio.com/src/contrib/mdsr_0.1.4.tar.gz'
Content type 'unknown' length 3926996 bytes (3.7 MB)
==================================================
downloaded 3.7 MB

* installing *source* package ‘dplyr’ ...
** package ‘dplyr’ successfully unpacked and MD5 sums checked
** libs
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c RcppExports.cpp -o RcppExports.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c address.cpp -o address.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c api.cpp -o api.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c arrange.cpp -o arrange.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c between.cpp -o between.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c bind.cpp -o bind.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c combine_variables.cpp -o combine_variables.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c distinct.cpp -o distinct.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c encoding.cpp -o encoding.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c filter.cpp -o filter.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c group_by.cpp -o group_by.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c group_indices.cpp -o group_indices.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c hybrid.cpp -o hybrid.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c hybrid_count.cpp -o hybrid_count.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c hybrid_debug.cpp -o hybrid_debug.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c hybrid_in.cpp -o hybrid_in.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c hybrid_minmax.cpp -o hybrid_minmax.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c hybrid_nth.cpp -o hybrid_nth.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c hybrid_offset.cpp -o hybrid_offset.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c hybrid_simple.cpp -o hybrid_simple.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c hybrid_window.cpp -o hybrid_window.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c init.cpp -o init.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c join.cpp -o join.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c join_exports.cpp -o join_exports.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c mutate.cpp -o mutate.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c rlang-export.c -o rlang-export.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c select.cpp -o select.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c set.cpp -o set.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c slice.cpp -o slice.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c summarise.cpp -o summarise.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c test.cpp -o test.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c utils.cpp -o utils.o
g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I/usr/local/include -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/bindrcpp/include" -I"/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/plogr/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c window.cpp -o window.o
g++ -m64 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o dplyr.so RcppExports.o address.o api.o arrange.o between.o bind.o combine_variables.o distinct.o encoding.o filter.o group_by.o group_indices.o hybrid.o hybrid_count.o hybrid_debug.o hybrid_in.o hybrid_minmax.o hybrid_nth.o hybrid_offset.o hybrid_simple.o hybrid_window.o init.o join.o join_exports.o mutate.o rlang-export.o select.o set.o slice.o summarise.o test.o utils.o window.o -L/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/StanHeaders/lib -lStanHeaders -L/usr/lib64/R/lib -lR
installing to /home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/dplyr/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in unloadNamespace(pkg_name) : 
  namespace ‘dplyr’ is imported by ‘sparklyr’ so cannot be unloaded
* removing ‘/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/dplyr’
Warning in install.packages :
  installation of package ‘dplyr’ had non-zero exit status
* installing *source* package ‘dbplyr’ ...
** package ‘dbplyr’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘dplyr’ 0.5.0 is already loaded, but >= 0.5.0.9004 is required
ERROR: lazy loading failed for package ‘dbplyr’
* removing ‘/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/dbplyr’
Warning in install.packages :
  installation of package ‘dbplyr’ had non-zero exit status
ERROR: dependency ‘dbplyr’ is not available for package ‘mdsr’
* removing ‘/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/mdsr’
Warning in install.packages :
  installation of package ‘mdsr’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpGlAscr/downloaded_packages’

**Comment by beanumber** [comment]
Hmmm... I'm seeing this in the log @gmichel-SMU posted:

```
Error in unloadNamespace(pkg_name) :
namespace ‘dplyr’ is imported by ‘sparklyr’ so cannot be unloaded
removing ‘/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/dplyr’
Warning in install.packages :
installation of package ‘dplyr’ had non-zero exit status
installing source package ‘dbplyr’ ...
** package ‘dbplyr’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
namespace ‘dplyr’ 0.5.0 is already loaded, but >= 0.5.0.9004 is required
ERROR: lazy loading failed for package ‘dbplyr’
```
It looks like you already have version 0.5.0 of `dplyr` loaded, and that is blocking something. 

Can you try:

```
update.packages()
install.packages("mdsr")
```
and report back what you see? The current version of `dplyr` is 0.7.3, and there have been some major changes in recent updates.

**Comment by gmichel-SMU** [comment]
Both commands did produce the same error:


** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in unloadNamespace(pkg_name) : 
  namespace ‘dplyr’ is imported by ‘sparklyr’ so cannot be unloaded
* removing ‘/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/dplyr’
Warning in install.packages :
  installation of package ‘dplyr’ had non-zero exit status
* installing *source* package ‘dbplyr’ ...
** package ‘dbplyr’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘dplyr’ 0.5.0 is already loaded, but >= 0.5.0.9004 is required
ERROR: lazy loading failed for package ‘dbplyr’
* removing ‘/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/dbplyr’
Warning in install.packages :
  installation of package ‘dbplyr’ had non-zero exit status
ERROR: dependency ‘dbplyr’ is not available for package ‘mdsr’
* removing ‘/home/rstudio/R/x86_64-redhat-linux-gnu-library/3.3/mdsr’
Warning in install.packages :
  installation of package ‘mdsr’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpnijki8/downloaded_packages’
> remove.packages("dplyr", lib="/usr/lib64/R/library")
Updating HTML index of packages in '.Library'
Warning in remove.packages :
  cannot create file '/usr/share/doc/R-3.3.2/html/packages.html', reason 'Read-only file system'
Warning in remove.packages :
  cannot update HTML package index
> remove.packages("dplyr", lib="/usr/lib64/R/library")
Updating HTML index of packages in '.Library'
Warning in remove.packages :
  cannot create file '/usr/share/doc/R-3.3.2/html/packages.html', reason 'Read-only file system'
Warning in remove.packages :
  cannot update HTML package index
>

**Comment by nicholasjhorton** [comment]
Is the R 3.3 the problem?  I'd suggest updating that as well. 

All the best,

Nick

**Comment by beanumber** [comment]
`Read-only file system` doesn't sound good. 

Can you try restarting your R session? It looks like having `sparklyr` loaded is causing a problem. 

I think your problem is not with `mdsr`. If you can't install/upgrade `dplyr`, then it's not a surprise that `mdsr` won't install.

**Comment by beanumber** [comment]
I think it's safe to close this?
