### ISSUE TITLE
mosaic error on Windows?

### ISSUE THREAD

**Issue by beanumber** [beanumber/mdsr#28]
(https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/mdsr-00check.html)

```
Version: 0.1.4
Check: loading without being on the library search path
Result: WARN
    -- Attaching packages --------------------------------------- tidyverse 1.2.1 --
    v ggplot2 2.2.1 v purrr 0.2.4
    v tibble 1.3.4 v dplyr 0.7.4
    v tidyr 0.7.2 v stringr 1.2.0
    v readr 1.1.1 v forcats 0.2.0
    -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    x dplyr::filter() masks stats::filter()
    x dplyr::lag() masks stats::lag()
    Loading required package: lattice
    Error in unloadNamespace(package) :
     namespace 'lattice' is imported by 'nlme', 'Matrix', 'psych', 'mosaic' so cannot be unloaded
    Error : .onAttach failed in attachNamespace() for 'mdsr', details:
     call: library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc,
     error: Package 'lattice' version 0.20.35 cannot be unloaded
    Error: package or namespace load failed for 'mdsr'
    Execution halted
    
    It looks like this package has a loading problem when not on .libPaths:
    see the messages for details.
Flavor: r-oldrel-windows-ix86+x86_64
```

[Nevermind the absurdity of supporting old releases on Windows...]

Is this a problem with `mosaic`? Or perhaps the combination of `tidyverse` and `mosaic`? 

Can @nicholasjhorton @dtkaplan @rpruim shed any light on this? I don't know how to reproduce this, let alone fix it. 

There is some urgency here as CRAN wants this done by the end of next week.

**Comment by nicholasjhorton** [comment]
Alas, I have no insights or guidance on this front.  @dtkaplan?

**Comment by rpruim** [comment]
It looks like the issue is related to pulling in lattice (which several packages are doing).  Not sure why there is an attempt to unlaod lattice here.

Are you able to recreate this, or it is just showing up in CRAN reports?

**Comment by beanumber** [comment]
It's just showing up on CRAN reports (see link above).

**Comment by beanumber** [comment]
I guess I'll just resubmit to CRAN and cross my fingers?

**Comment by rpruim** [comment]
If `devtools::build_win()` doesn't complain and things are working on your system, I think that's the way to go.  Hard to debug something that we can't recreate and don't fully understand.

**Comment by beanumber** [comment]
@rpruim Yeah, totally agree. 

[CRAN accepted](https://cran.r-project.org/web/packages/mdsr/)!
