### ISSUE TITLE
Package 'airlines': installation and data access problem 

### ISSUE THREAD

**Issue by ghost** [beanumber/mdsr#29]
**Environment is Windows 8.1, RStudio 1.1.423 and R-3.4.3 (64 bit).**

**1. *Rd warning* when installing a recent version of the 'airlines' package with renewed URL**

`devtools::install_github("beanumber/airlines", force=TRUE)`

results in several Rd warnings like

> Rd warning: C:/Users/ulk/AppData/Local/Temp/RtmpGeTiCt/devtools1aac49536e3a/beanumber-airlines-0089136/man/etl_load.etl_airlines.Rd:33: missing file link 'src_mysql'

Any solution available to avoid the Rd warnings?

**2. Data access problem which might be due to a change in the data base columns.**

After setup
```
library(airlines)
# use default temporary directory and SQLite database
airlines <- etl("airlines")
```
the command
```
airlines %>%
   etl_update(year = 1987, months = 11)
```
delivers the following access errors

> 
> 
> ...
> Downloading flight data...
> Downloading 1 new files.  0 untouched.
> trying URL 'http://transtats.bts.gov/PREZIP/On_Time_On_Time_Performance_1987_11.zip'
> Content type 'application/x-zip-compressed' length 8045196 bytes (7.7 MB)
> downloaded 7.7 MB
> 
> Multiple files in zip: reading 'On_Time_On_Time_Performance_1987_11.csv'
> Parsed with column specification:
> cols(
>   .default = col_character(),
>   Year = col_integer(),
>   Quarter = col_integer(),
>   Month = col_integer(),
>   DayofMonth = col_integer(),
>   DayOfWeek = col_integer(),
>   FlightDate = col_date(format = ""),
>   AirlineID = col_integer(),
>   FlightNum = col_integer(),
>   OriginAirportID = col_integer(),
>   OriginAirportSeqID = col_integer(),
>   OriginCityMarketID = col_integer(),
>   OriginWac = col_integer(),
>   DestAirportID = col_integer(),
>   DestAirportSeqID = col_integer(),
>   DestCityMarketID = col_integer(),
>   DestWac = col_integer(),
>   DepDelay = col_double(),
>   DepDelayMinutes = col_double(),
>   DepDel15 = col_double(),
>   DepartureDelayGroups = col_integer()
>   \# ... with 11 more columns
> )
> See spec(...) for full column specifications.
> |=============================================================================================================================| 100%  167 MB
> Error in overscope_eval_next(overscope, expr) :
>   object 'DepTime' not found
> In addition: Warning message:
> Missing column names filled in: 'X110' [110] 

How to resolve that?

Thanks.

**Comment by beanumber** [comment]
This is really an issue with (https://github.com/beanumber/airlines/issues) -- not `mdsr`

I suspect that this was fixed by (https://github.com/beanumber/airlines/commit/58231c3cf15855117d21acd9b70fe1bb1e9d0c79). Can @ulk56 confirm that this is still an issue?
