### ISSUE TITLE
fix non-ASCII characters in Cuisines

### ISSUE THREAD

**Issue by beanumber** [beanumber/mdsr#3]
```
* checking data for non-ASCII characters ... WARNING
  Note: found 151 marked UTF-8 strings
  Warning: found non-ASCII string
  'Caf<e9>/Coffee/Tea' in object 'Cuisines'
```

(https://github.com/nicholasjhorton/DataScience/issues/54)

**Comment by nicholasjhorton** [comment]
I couldn't run:
load("~/Dropbox/lib/mdsr/data/MyRestaurants.rda")

in data-raw/MyRestaurants.R

Just FYI, here's another way to figure out what's what in the offending cuisine_description:

> tools::showNonASCII(Cuisines$cuisine_description)
> 36: Caf<e9>/Coffee/Tea

**Comment by beanumber** [comment]
Of course, but again, we don't have a reproducible set of code to produce `MyRestaurants` in the first place, right? 

Do you know how to fix the bug?

**Comment by nicholasjhorton** [comment]
I think that:

Cuisines$cuisine_description[36] = "Cafe/Coffee/Tea"

should do the trick.

**Comment by beanumber** [comment]
Except that it's a factor. Also that doesn't clear the NOTE. I'm thinking something more like:

```
x <- as.character(Cuisines$cuisine_description)
Encoding(x) <- "UTF-8"
iconv(x, "UTF-8", "ASCII"
```

But that doesn't quite work. Any other ideas?

**Comment by nicholasjhorton** [comment]
While we working this problem I would prefer if we could turn the factors into character vectors. 

All the best,

Nick

**Comment by beanumber** [comment]
Done. I fixed the `WARNING` but left the `NOTE`. There were other UTF characters in the `Restaurants` data frame. 

```
* checking data for non-ASCII characters ... NOTE
  Note: found 1 marked Latin-1 string
  Note: found 151 marked UTF-8 strings
```
