### ISSUE TITLE
on mdsr server, imdb and fec lacking talbles

### ISSUE THREAD

**Issue by homerhanumat** [beanumber/mdsr#32]
At the moment the server` mdsr.cdc7tgkkqd0n.us-east-1.rds.amazonaws.com` shows two databases (imdb and fec) that have no tables.  Are there plans to repopulate them?  (I would like to use them in a Spring 2019 class.)

**Comment by beanumber** [comment]
Let me look into it. I'll see how much space we have left.

**Comment by beanumber** [comment]
`imdb` is now there

**Comment by beanumber** [comment]
Closing this, as #36 includes the question about what to populate on the AWS Server.
