### ISSUE TITLE
medicareProviders and related datasets

### ISSUE THREAD

**Issue by homerhanumat** [beanumber/mdsr#39]
The data set `MedicareCharges` defines the variable `drg` as a Direct Recovery Group, but DRG in this context is actually an acronym for Diagnostic Related Group (see [https://hmsa.com/portal/provider/zav_pel.fh.DIA.650.htm](https://hmsa.com/portal/provider/zav_pel.fh.DIA.650.htm)).  In addition, the help file mentions the data set `DirectRecoveryGroups` which is not included in package **mdsr**.

Presumably the data sets `MedicareCharges` and `MedicareProviders` are taken from package [**DataComputing**](https://github.com/DataComputing/DataComputing), where one also finds `DirectRecoveryGroups`.  Of course `DirectRecoveryGroups` should be renamed to `DiagnosticRelatedGroups`, and material in `data.R` should be modified accordingly.

**Comment by beanumber** [comment]
@dtkaplan can you weigh in on this?

**Comment by beanumber** [comment]
Thanks @homerhanumat !
