### ISSUE TITLE
consider suppressing part or all of this output

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/mdsr#42]
In accordance with CRAN policy, the 'mdsr' package 
           no longer attaches
the 'tidyverse' package automatically.
You may need to 'library(tidyverse)' in order to 
           use certain functions.

**Comment by beanumber** [comment]
Agreed. I also think the package should not load `mosaic`.

**Comment by nicholasjhorton** [comment]
Thanks for your updates.

I hear where you are coming from.  But I wonder if we can keep mosaic for the time being (or at least hold off on making a decision for now).

**Comment by beanumber** [comment]
What about re-exporting any `mosaic` functions we are still using from `mdsr`? Would that help?

**Comment by nicholasjhorton** [comment]
The fact that mosaic loads dplyr is a big reason for me to build upon it.  I realize that you may disagree with this approach and will let you make your final determination.  I just think it's simpler for students to be able to do some useful things after running:

library(mdsr)

**Comment by beanumber** [comment]
Yeah, I want them to do

```
library(tidyverse)
library(mdsr)
```

You're coasting on the fact that `mdsr` loads `mosaic`, which loads `dplyr` and `ggformula` via Depends. 

But what about all of the students who aren't using `mosaic`? They won't even realize which packages are being attached and which functions are then available to them. For my students, I would rather have them understand "Oh, I have to load the `tidyverse`", and then if there is additional `mdsr` functionality then they can load that. 

But what happens in your case when one of your students wants to use `pivot_longer()`? Or `str_detect()`?

**Comment by nicholasjhorton** [comment]
I had thought that we were going to be adding explicit library() calls or use of tidyr::pivot_longer() references for functions outside of the mdsr/mosaic/dplyr universe.

That being said, I can't refute your reasoning and expected that you'd want to make this shift.  I'm not standing in the way of the change. I just suspect that it will move the pain point earlier.
