### ISSUE TITLE
update DataSciencePapers

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/mdsr#43]
There are now 1,089 papers that match "Data Science" in the text chapter.  I've updated the package with the new dataset.  Is it too large?  Do we need to deal with this in some alternative manner?  

https://github.com/beanumber/mdsr/blob/master/data/DataSciencePapers.rda

**Comment by beanumber** [comment]
It's about 0.5 MB. I made it a tibble and changed the compression.
