### ISSUE TITLE
drop mosaic dependency

### ISSUE THREAD

**Issue by beanumber** [beanumber/mdsr#48]
@nicholasjhorton , I think we should drop the `mosaic` dependency for this package. We don't need it or use it, and it's not best practice to force users to install all of the `mosaic` dependencies just to install this package for the book (which should be lightweight). 

`library(mdsr)` doesn't attach `mosaic` anyway, so users will already have to `library(mosaic)` separately. The only change to users here is that they would have to install `mosaic` separately. 

We should make a quick decision about this before CRAN submission.

**Comment by nicholasjhorton** [comment]
I'm find with dropping mosaic as a dependency: I had thought that you'd already made this change.
