### ISSUE TITLE
Broken Link to `Issues` Page

### ISSUE THREAD

**Issue by math-mcshane** [beanumber/mdsr#61]
How exactly did I find my way here, you ask? Hacking the URL. 

On the homepage for the web edition, https://mdsr-book.github.io/mdsr2e/ , the link inside 

> "To submit corrections, please visit our [GitHub repository](https://github.com/mdsr-book/mdsr2e/issues) and file an issue" 

points to https://github.com/mdsr-book/mdsr2e/issues which (apparently?) should be https://github.com/mdsr-book/mdsr/issues . At the very least, it's currently giving a `404`. 

I guess while I'm at it -- the link the first edition on this same page is broken as well (and there does not appear to be a substitute). 

Apologies if you were aware. Also, I don't have a separate issue to report -- I was trying to find the way you presented the citation for this book.

**Comment by nicholasjhorton** [comment]
@math-mcshane thanks for noting the issue.  We will investigate both issues.

**Comment by beanumber** [comment]
The problem is that the `mdsr2e` repo is still private. I suggest that we make it public. This will solve the problem without having to change the link. 

Alternatively, we could use the `mdsr` repo, but that is for the *package*, not the book, so it would make things less straightforward, I think. 

@nicholasjhorton what would you like to do?

**Comment by nicholasjhorton** [comment]
I worry that making the mdsr2e repo public would violate our agreement with the publisher.  

I would prefer to either:

1. Have the link point to the mdsr package repo, or
2. Create a separate shell mdsr2e_public repo where these discussions could be located.

**Comment by beanumber** [comment]
I will implement (2). I don't like (1). 

It might make even more sense to have the HTML served from `mdsr2e`, and make this repo public, and then move the source files to `mdsr2e_src` and keep that one private.

**Comment by nicholasjhorton** [comment]
Does your alternative 2b mean that we need to scrub all of the commits out of the existing repo? Or do some sort of a flip?  (It sounds beyond my skills.)

**Comment by beanumber** [comment]
Yes, it would.

**Comment by beanumber** [comment]
The URL has now been changed to: https://github.com/mdsr-book/mdsr-book.github.io/issues

**Comment by nicholasjhorton** [comment]
Nice! Thanks for your work on this front.
