### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by willwerscheid** [beanumber/mdsr#64]
Hi! `mdsr` was apparently removed from CRAN on 10/5 and can no longer be installed via `install.packages()`.

**Comment by beanumber** [comment]
Sorry. I'll resubmit as soon as I can.

**Comment by nicholasjhorton** [comment]
In the interim, the package can be downloaded using the following command:

`devtools::install_github("mdsr-book/mdsr")`

**Comment by nicholasjhorton** [comment]
@beanumber any updates on this front (or for #65)? Thanks as always for your efforts.

**Comment by nicholasjhorton** [comment]
Is the CRAN issue something that we can address? Does it involve changes to package dependencies?

**Comment by beanumber** [comment]
I'm working on it...

**Comment by beanumber** [comment]
Submitted to CRAN yesterday...

**Comment by nicholasjhorton** [comment]
Thanks!

**Comment by willwerscheid** [comment]
Thank you! Looking forward to using the textbook this semester (first time!).

**Comment by beanumber** [comment]
Should be back on CRAN soon!
