### ISSUE TITLE
6.4.4 Example: Japanese nuclear reactors

### ISSUE THREAD

**Issue by Tolstik2004** [beanumber/mdsr#67]
when I copy this code in Rstudio:

tables <- "http://en.wikipedia.org/wiki/List_of_nuclear_reactors" %>%
  read_html() %>% 
  html_nodes(css = "table")

idx <- tables %>%
  html_text() %>%
  str_detect("Fukushima Daiichi") %>%
  which()

reactors <- tables %>%
  purrr::pluck(idx) %>%
  html_table(fill = TRUE) %>%
  janitor::clean_names() %>%
  rename(
    reactor_type = reactor,
    reactor_model = reactor_2,
    capacity_net = capacity_in_mw,
    capacity_gross = capacity_in_mw_2
  ) %>%
  tail(-1)

I get the following error message:

" Error in `pluck_raw()`:
! Index 1 must have length 1, not 0."

Can you help me with this issue, please? Thanks.

**Comment by Tolstik2004** [comment]
I already corrected the issue,the link: "http://en.wikipedia.org/wiki/List_of_nuclear_reactors", no longer exists, it was modified in Wikipedia.

**Comment by beanumber** [comment]
This issue has been updated and corrected in the third edition:

https://mdsr-book.github.io/mdsr3e/06-dataII.html#sec-nukes
