### ISSUE TITLE
Could not download "mdsr" package 

### ISSUE THREAD

**Issue by Aovalle1990** [beanumber/mdsr#7]
Code used:
install.packages("devtools")
devtools::install_github("beanumber/mdsr")
require(mdsr)
error =
Loading required package: mdsr
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘mdsr’

**Comment by beanumber** [comment]
Did you incur errors during the installation process? I suspect that the `car` dependency for `mosaic` is to blame here. 

(https://github.com/ProjectMOSAIC/mosaic/issues/287)

What version of the `car` package do you have installed?

**Comment by beanumber** [comment]
Another student with the same error:

```
devtools::install_github("ProjectMOSAIC/mosaic")
```

```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘nlme’ 3.1-122 is being loaded, but >= 3.1.123 is required
ERROR: lazy loading failed for package ‘mosaic’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mosaic’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mosaic’
Error: Command failed (1)
```

@rpruim what is the preferred solution here?

**Comment by Aovalle1990** [comment]
Yes indeed, this the error that shows up;

Loading required package: mosaic
Loading required package: lattice
Loading required package: ggplot2
Loading required package: car
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck
= vI[[j]]) :
  namespace ‘pbkrtest’ 0.4-2 is being loaded, but >= 0.4.4 is required
In addition: Warning messages:
1: package ‘mosaic’ was built under R version 3.2.3
2: package ‘ggplot2’ was built under R version 3.2.3
3: package ‘car’ was built under R version 3.2.3
Failed with error:  ‘package ‘car’ could not be loaded’

On Sat, Feb 20, 2016 at 10:35 AM, Ben Baumer notifications@github.com
wrote:

> Another student with the same error:
> 
> devtools::install_github("ProjectMOSAIC/mosaic")
> 
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
>   namespace ‘nlme’ 3.1-122 is being loaded, but >= 3.1.123 is required
> ERROR: lazy loading failed for package ‘mosaic’
> - removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mosaic’
> - restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mosaic’
>   Error: Command failed (1)
> 
> @rpruim https://github.com/rpruim what is the preferred solution here?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beanumber/mdsr/issues/7#issuecomment-186630092.

## 

Andrea Ovalle
Ada Recruitment Intern
Neuroscience Major
andreada18.tumblr.com
Smith College
AC'18

**Comment by beanumber** [comment]
What happens if you do:

```
install.packages("car")
```

?

Also, try:

```
update.packages()
```

and then try to install `mosaic` again.

**Comment by Aovalle1990** [comment]
I tried that ... did not work 

> install.packages("car")
> Warning in install.packages :
>   dependency ‘pbkrtest’ is not available
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 32 1401k   32  457k    0     0   428k      0  0:00:03  0:00:01  0:00:02  428k 68 1401k   68  956k    0     0   467k      0  0:00:02  0:00:02 --:--:--  467k 82 1401k   82 1154k    0     0   378k      0  0:00:03  0:00:03 --:--:--  378k100 1401k  100 1401k    0     0   373k      0  0:00:03  0:00:03 --:--:--  373k

The downloaded binary packages are in
    /var/folders/02/k2q25_4n1n1fq7fmw7pxjj3m0000gn/T//RtmpHnrVY5/downloaded_packages

> install.packages("mosaic")
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  4 3938k    4  176k    0     0   502k      0  0:00:07 --:--:--  0:00:07  501k 43 3938k   43 1714k    0     0  1264k      0  0:00:03  0:00:01  0:00:02 1264k 65 3938k   65 2562k    0     0  1088k      0  0:00:03  0:00:02  0:00:01 1088k 77 3938k   77 3058k    0     0   848k      0  0:00:04  0:00:03  0:00:01  848k 83 3938k   83 3282k    0     0   754k      0  0:00:05  0:00:04  0:00:01  754k 89 3938k   89 3506k    0     0   655k      0  0:00:06  0:00:05  0:00:01  666k 93 3938k   93 3666k    0     0   576k      0  0:00:06  0:00:06 --:--:--  390k 96 3938k   96 3794k    0     0   496k      0  0:00:07  0:00:07 --:--:--  232k 96 3938k   96 3810k    0     0   452k      0  0:00:08  0:00:08 --:--:--  155k100 3938k  100 3938k    0     0   455k      0  0:00:08  0:00:08 --:--:--  152k

The downloaded binary packages are in
    /var/folders/02/k2q25_4n1n1fq7fmw7pxjj3m0000gn/T//RtmpHnrVY5/downloaded_packages

> require(car)
> Loading required package: car
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   namespace ‘pbkrtest’ 0.4-2 is being loaded, but >= 0.4.4 is required
> In addition: Warning message:
> package ‘car’ was built under R version 3.2.3

**Comment by Aovalle1990** [comment]
what is "pbkrtest"

**Comment by nicholasjhorton** [comment]
I've seen others having trouble installing car because of this.  Some thoughts:

(1) are you running R 3.2.3?

(2) if not, can you install pbkrtest from source?

Sorry for the complications,

Nick

> On Feb 20, 2016, at 11:38 AM, Aovalle1990 notifications@github.com wrote:
> 
> what is "pbkrtest"
> 
> —
> Reply to this email directly or view it on GitHub.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by beanumber** [comment]
`pbkrtest` is a dependency of `car`. Can you try:

```
install.packages("pbkrtest", type = "source")
```

If that works, then try to install `car` and then `mosaic` and then `mdsr`.

**Comment by Aovalle1990** [comment]
Success ! 
I feel kind of silly, I realized that I need it to update R not Rstudio, once I did that I was able to download the package. 

Thank you

**Comment by nicholasjhorton** [comment]
It still shouldn't be this difficult to install the package: thanks for alerting us.

Nick

> On Feb 20, 2016, at 1:58 PM, Aovalle1990 notifications@github.com wrote:
> 
> Success ! 
> I feel kind of silly, I realized that I need it to update R not Rstudio, once I did that I was able to download the package.
> 
> Thank you
> 
> —
> Reply to this email directly or view it on GitHub.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
