### ISSUE TITLE
typo in v3

### ISSUE THREAD

**Issue by hardin47** [beanumber/mdsr#70]
I think there is a typo here (16.1.5 in V3):

> However, because the cardinality of the index on tailnum is smaller that the cardinality of the index on year (see [Table 16.1](https://mdsr-book.github.io/mdsr3e/16-sqlII.html#tbl-show-indexes)), the number of rows in flights associated with each unique value of tailnum is smaller than for each unique value of year. Thus, the first query runs faster.

The cardinality of tailnum is larger than year.  But, yes you are right, the rows searched in the join will therefore be much smaller when using tailnum.

**Comment by beanumber** [comment]
Yeah, you're right. We've confused `x` and `1/x`. 

Note that cardinality times rows consulted are roughly equal to 48 million for both indices:

```
> 37862 * 1266
[1] 47933292
> 6450117 * 7
[1] 45150819
```

Easiest fix is just to change "smaller" to "larger" in the quote above, right?

**Comment by hardin47** [comment]
right, just change the word from smaller to larger.  That's what I'd do.

**Comment by beanumber** [comment]
Thanks, Jo! 

Fixed via https://github.com/mdsr-book/mdsr3e/commit/02b338b46c66241c36f230529e9a2bb2afeebbbc
