### ISSUE TITLE
migrate RDS server from MySQL 5.7 to MariaDB 10

### ISSUE THREAD

**Issue by beanumber** [beanumber/mdsr#72]

**Comment by beanumber** [comment]
This is done. Note that no changes to the `mdsr` package are necessary. 

``` r
library(mdsr)
db <- dbConnect_scidb("airlines")
str(db)
#> Formal class 'MariaDBConnection' [package "RMariaDB"] with 7 slots
#>   ..@ ptr                   :<externalptr> 
#>   ..@ host                  : chr "mdsr.cdc7tgkkqd0n.us-east-1.rds.amazonaws.com"
#>   ..@ db                    : chr "airlines"
#>   ..@ load_data_local_infile: logi FALSE
#>   ..@ bigint                : chr "integer64"
#>   ..@ timezone              : chr "UTC"
#>   ..@ timezone_out          : chr "UTC"
```

<sup>Created on 2024-02-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

@nicholasjhorton Please also note that **only years 2013-2015 of the `flights` data are present on the server**. I've changed all of the code in the book and the examples to reflect that.

**Comment by nicholasjhorton** [comment]
Thanks for the heads up: this was quite timely. I've alerted the other STAT231 (Data Science) instructor at Amherst.
