### ISSUE TITLE
Election Statistics codebook

### ISSUE THREAD

**Issue by santiago-alles** [beanumber/mdsr#73]
The codebook of the "Elections" dataset is messed up. Some variables do not correspond to the description, some variables in the data do not appear in the codebook, and variables in the codebook are not included in the dataset.

**Comment by nicholasjhorton** [comment]
Ack. Indeed. I see what you mean. Something has gotten jumbled. Thanks for alerting us to the issue: we will investigate.

**Comment by beanumber** [comment]
It seems that this was never correct. I traced it back to here:

https://github.com/mdsr-book/mdsr/commit/b5fef9e9faf86025d0fe77fdc21f1b95623e6e17

Will fix.
