### ISSUE TITLE
Inaccurate references to table

### ISSUE THREAD

**Issue by idtemp** [beanumber/mdsr#8]
On pages 87-88 (section 4.1.2) there are a few references to "Ahmed," "Ahmet" (a possible misspelling?), and "Sherina" in Table 4.1, but I am unable to locate any of these names on the indicated table or any other table.

**Comment by beanumber** [comment]
Good catch! 

This was caused by the recent update to the `babynames` package, which now includes the 2014 data. I will fix this.
